apiVersion: www.hydrovu.com/v1
kind: Combine
name: noyo-data
desc: Noyo harbor instrument collections
spec:
  scopes:
  - name: FieldStation
    columns:
    # Wanting to use the EXCLUDE/EXCEPT syntax but sea-query doesn't go there.
    - Surface pH
    - Surface Temp
    - Surface Chl-a
    - Surface DO
    - Surface Salinity
    - Surface Depth
    - Bottom Temp
    - Bottom DO
    - Bottom Salinity
    - Bottom Depth
    - Baro
    - Battery Level
    series:
    - pattern: {{ derive }}/SurfaceMeasurements/*
    - pattern: {{ derive }}/BottomMeasurements/*
    - pattern: {{ derive }}/VulinkMeasurements/*

  # - name: BDock
  #   series:
  #   - pattern: {{ hydrovu }}/data-6154708427603968
  #     attrs:
  #       source: in-situ
  #       device: at500
  #       where: surface
  #   - pattern: {{ hydrovu }}/data-4990594334457856
  #     attrs:
  #       source: in-situ
  #       device: vulink
  #       where: surface
  # - name: Princess
  #   series:
  #   - pattern: {{ hydrovu }}/data-6187749627789312
  #     attrs:
  #       source: in-situ
  #       device: at500
  #       where: surface
  #   - pattern: {{ hydrovu }}/data-5877040213786624
  #     attrs:
  #       source: in-situ
  #       device: vulink
  #       where: surface
  # - name: Silver
  #   series:
  #   - pattern: {{ hydrovu }}/data-5859376846209024
  #     attrs:
  #       source: in-situ
  #       device: at500
  #       where: surface
  #   - pattern: {{ hydrovu }}/data-6582334615060480
  #     attrs:
  #       source: in-situ
  #       device: vulink
  #       where: surface
  #   - pattern: {{ hydrovu }}/data-6417476404772864
  #     attrs:
  #       source: in-situ
  #       device: vulink
  #       where: surface
        
