apiVersion: www.hydrovu.com/v1
kind: Combine
name: noyodata
desc: Noyo harbor instrument collections
spec:
  scopes:
  - name: FieldStation
    series:
    - pattern: "/Derive/csvextract/SurfaceMeasurements/*"
    - pattern: "/Derive/csvextract/BottomMeasurements/*"
    - pattern: "/Derive/csvextract/VulinkMeasurements/*"

  # - name: BDock
  #   series:
  #   - pattern: "{{ hydrovu }}/data/BDockVulink*"
  #   - pattern: "{{ hydrovu }}/data/BDockAT500*"
  # - name: Princess
  #   series:
  #   - pattern: "{{ hydrovu }}/data/PrincessVulink*"
  #   - pattern: "{{ hydrovu }}/data/PrincessAT500*"
  # - name: Silver
  #   series:
  #   # Note Silver has two Vulinks matching, one a replacement.
  #   - pattern: "{{ hydrovu }}/data/SilverVulink*"
  #   - pattern: "{{ hydrovu }}/data/SilverAT500*"

