apiVersion: github.com/jmacd/duckpond/v1
kind: Observable
name: noyosite
desc: Templates
spec:
  collections:
  - name: hello
    pattern: "{{ combine }}/*/combine"
    template: |
      BIGTMPL
      {% for field in schema.fields %}
        FIELD {{ field.name }} {{ field.unit }} in {{ field.instrument }}
      {% endfor %}
      YOEND
