apiVersion: github.com/jmacd/duckpond/v1
kind: Template
name: noyosite
desc: Observable framework generator
spec:
  collections:
  - name: hello
    in_pattern: "/Reduce/ca5a6baf-7787-40c2-beb5-42dfe7484bcc/single_instrument/name=*/res=1h"
    out_pattern: "$0.md"
    template: |-
      ---
      toc: false
      title: Water Quality
      ---
      ```js
      import {schemeObservable10} from "npm:d3-scale-chromatic";
      ```

      ```js
      html`<link type="text/css" href="${await FileAttachment('style.css').url()}" rel="stylesheet" />`
      ```

      <div class="hero">
              <h1>Noyo Harbor Blue Economy</h1>
              <h2>Quality detail</h2>
      </div>

      <details>
        <summary>Controls</summary>

      ```js
      const timelist = [
        ["1 Week", 7],
        ["2 Weeks", 14],
        ["1 Month", 30],
        ["2 Months", 60],
        ["3 Months", 90],
        ["6 Months", 180]
      ];
      
      const timepick = view(
        Inputs.radio(
          new Map(timelist),
          {
                      value: 7, 
                      label: "Time range", 
                      format: (t) => {
                  return html`<span style="
                font-size: 1.5vw;
                font-weight: 300;
                line-height: 1;
              ">${t[0]}</span>`
                }
              }
        )
      );
      ```

      ```js
      // Timestamps are in milliseconds
      const now = new Date().getTime();
      
      // 24 days, 3600 secs/hour, 1000 ms/sec
      const begin = now - timepick * 24 * 3600 * 1000;

      var datafiles = {
      {%- for k2, v2 in export[args[0]] %}
        "{{ k2 }}": [
        {%- for v3 in v2 %}
          {
            "start_time": {{ v3.start_time }},
            "end_time": {{ v3.end_time }},
            "file": FileAttachment("{{ v3.file }}"),
          },
        {%- endfor %}
        ],
      {%- endfor %}
      };

      var duck = await DuckDBClient.of({
      })
      ```

      ```js
      var all = await duck.query(`select * from read_parquet(${JSON.stringify(datafiles["res=1h"].map((f) => f.file.href))})`);
      ```
      
      </details>

      <details>
        <summary>Raw data</summary>

      ```js
      view(Inputs.table(all));
      ```
      </details>
      
      <div class="grid grid-cols-1">
      {% for key, fields in group(by="name",in=schema.fields) %}
        <div class="card">${
          resize((width) => Plot.plot({
            title: "{{ key }}",
            width,
            x: {grid: true, type: "time", label: "Date", domain: [begin, now]},
            y: {grid: true, label: "{{ fields[0].unit }}", zero: true},
            color: {legend: true},
            marks: [
            {% for field in fields -%}
              Plot.lineY(all, {x: "Timestamp", y: "{{ field.instrument }}.{{ field.name }}.{{ field.unit }}.{{ field.agg }}", stroke: schemeObservable10[{{ loop.index }}]}),
            {%- endfor %}
            ]
          }))
        }</div>
      {% endfor %}
      </div>
