apiVersion: duckpond/v1
kind: Reduce
name: downsampled
desc: Downsampled datasets
spec:
  collections:
  - name: single_site
    resolutions: [1h, 2h, 4h, 12h, 24h]
    datasets:
    - in_pattern: "/Combine/noyodata/*/combine"
      out_pattern: "site=$0"

  - name: single_param
    resolutions: [1h, 2h, 4h, 12h, 24h]
    datasets: 
    - in_pattern: "/Combine/noyodata/*/combine"
      out_pattern: "param=DO"
      columns:
      - "AT500_Bottom.DO.mg/L"
      - "AT500_Surface.DO.mg/L"

    - in_pattern: "/Combine/noyodata/*/combine"
      out_pattern: "param=Salinity"
      columns:
      - "AT500_Surface.Salinity.psu"
      - "AT500_Bottom.Salinity.psu"
