apiVersion: duckpond/v1
kind: Reduce
name: downsampled
desc: Downsampled datasets
spec:
  datasets:
  - name: single_site
    in_pattern: "/Combine/noyodata/*/combine"
    out_pattern: "site=$0"
    resolutions: [1h, 2h, 4h, 12h, 24h]

  - name: single_param
    in_pattern: "/Combine/noyodata/*/combine"
    out_pattern: "param=DO"
    resolutions: [1h, 2h, 4h, 12h, 24h]
    columns:
    - "AT500_Bottom.DO.mg/L"
    - "AT500_Surface.DO.mg/L"
