apiVersion: duckpond/v1
kind: Reduce
name: downsampled
desc: Downsampled datasets
spec:
  datasets:
  - name: single_instrument
    in_pattern: "/Combine/noyodata/*/combine"
    out_pattern: "reduce-$0"
    resolutions: [1h, 2h, 4h, 12h, 24h]
    queries:
      AT500_Surface.DO.mg/L: ["avg", "min", "max"]
