apiVersion: www.hydrovu.com/v1
kind: Combine
name: noyodata
desc: Noyo harbor instrument collections
spec:
  scopes:
  - name: FieldStation
    series:
    - pattern: "/Derive/csvextract/SurfaceMeasurements/*"
    - pattern: "/Derive/csvextract/BottomMeasurements/*"
    - pattern: "/Derive/csvextract/VulinkMeasurements/*"

  - name: BDock
    series:
    - pattern: "/HydroVu/noyoharbor/data/BDockVulink*"
    - pattern: "/HydroVu/noyoharbor/data/BDockAT500*"
  - name: Princess
    series:
    - pattern: "/HydroVu/noyoharbor/data/PrincessVulink*"
    - pattern: "/HydroVu/noyoharbor/data/PrincessAT500*"
  - name: Silver
    series:
    # Note Silver has two Vulinks matching, one a replacement.
    - pattern: "/HydroVu/noyoharbor/data/SilverVulink*"
    - pattern: "/HydroVu/noyoharbor/data/SilverAT500*"

