apiVersion: github.com/jmacd/duckpond/v1
kind: Template
name: noyosite
desc: Observable framework generator
spec:
  collections:
  - name: sites
    in_pattern: "/Reduce/downsampled/single_site/site=*/res=1h"
    out_pattern: "$0.md"
    template_file: "example/data.md.tmpl"
  - name: params
    in_pattern: "/Reduce/downsampled/single_param/param=*/res=1h"
    out_pattern: "$0.md"
    template_file: "example/data.md.tmpl"

