factory: sitegen

site:
  title: "Caspar Water"
  base_url: "/"
  site_url: "https://casparwater.us"

content:
  - name: "pages"
    pattern: "/content/*.md"

exports:
  - name: "metrics"
    pattern: "/reduced/*/*/*.series"
  - name: "analysis"
    pattern: "/analysis/*"

routes:
  - name: "home"
    type: static
    slug: ""
    page: "/site/index.md"
    routes:
      - name: "pages"
        type: content
        slug: ""
        content: "pages"
      - name: "data"
        type: static
        slug: "data"
        routes:
          - name: "metric-detail"
            type: template
            slug: "$0"
            page: "/site/data.md"
            export: "metrics"
      - name: "analysis"
        type: static
        slug: "analysis"
        routes:
          - name: "analysis-detail"
            type: template
            slug: "$0"
            page: "/site/analysis.md"
            export: "analysis"

partials:
  sidebar: "/site/sidebar.md"

static:
  - pattern: "/img/*"

sidebar:
  - "Political"
  - "Blog"
  - "History"
  - "Water"
  - "System"
  - "Monitoring"
  - "Software"
  - "Operator"
  - "Thanks"
