factory: sitegen

site:
  title: "Septic Station Monitor"
  base_url: "/"

exports:
  - name: "metrics"
    pattern: "/reduced/*/*/*.series"
    temporal: ["year", "month"]

routes:
  - name: "home"
    type: static
    slug: ""
    page: "/etc/site/index.md"
  - name: "data"
    type: static
    slug: "data"
    routes:
      - name: "metric-detail"
        type: template
        slug: "$0"
        page: "/etc/site/data.md"
        export: "metrics"

partials:
  sidebar: "/etc/site/sidebar.md"

static_assets: []
