apiVersion: github.com/jmacd/duckpond/v1
kind: Derive
name: welldepth
desc: Extract from CSV
spec:
  collections:
  - pattern: "/Inbox/rawdata/*.csv"
    name: WellDepth
    query: >
      SELECT
        Timestamp as T,
        Depth as D,
        FROM read_csv('$1')
      ORDER BY T
