apiVersion: duckpond/v1
kind: Reduce
name: downsampled
desc: Downsampled datasets
spec:
  collections:
  - name: caspar_water
    resolutions: [1h, 2h, 4h, 12h, 24h]
    datasets:
    - in_pattern: "/Derive/welldepth/WellDepth/*.csv"
      out_pattern: "well_depth"
