#!/bin/bash
# Browser validation for sitegen output.
#
# Each browser test runs once against the site it was designed for:
#   - 210, 211: root site (generated by test 201)
#   - 305: overlay site (generated by test 305)
#
# A subdir deployment (base_url: /myapp/) is tested by re-running
# 210 against a subdir site to verify base_url handling.
#
# Prerequisites: Node.js >=22, Docker
# First-time:    cd testsuite/browser && npm install
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TESTSUITE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TESTS_DIR="${SCRIPT_DIR}/tests"
PORT=4174
VITE_PID=""

# Forward --no-rebuild to run-test.sh calls
RUN_TEST_EXTRA_ARGS=()
for arg in "$@"; do
    case "$arg" in
        --no-rebuild|-n) RUN_TEST_EXTRA_ARGS+=("--no-rebuild") ;;
    esac
done

start_vite() {
    local site_root="$1"
    local base_path="${2:-/}"

    lsof -ti:${PORT} 2>/dev/null | xargs -r kill -9 2>/dev/null || true
    sleep 0.5

    SITE_ROOT="${site_root}" BASE_PATH="${base_path}" \
        npx vite --port ${PORT} --strictPort --config "${SCRIPT_DIR}/vite.config.js" &
    VITE_PID=$!

    local url="http://localhost:${PORT}${base_path}"
    for i in $(seq 1 30); do
        if curl -sf "${url}index.html" > /dev/null 2>&1; then
            echo "  ✓ Vite serving at ${url}"
            return 0
        fi
        sleep 1
    done
    echo "ERROR: Vite did not start within 30 seconds (tried ${url}index.html)"
    return 1
}

stop_vite() {
    if [[ -n "${VITE_PID}" ]]; then
        kill "${VITE_PID}" 2>/dev/null || true
        wait "${VITE_PID}" 2>/dev/null || true
        VITE_PID=""
    fi
    lsof -ti:${PORT} 2>/dev/null | xargs -r kill -9 2>/dev/null || true
}

cleanup() {
    stop_vite
}
trap cleanup EXIT

# Ensure dependencies are installed
if [[ ! -d "${SCRIPT_DIR}/node_modules" ]]; then
    echo "Installing browser test dependencies..."
    (cd "${SCRIPT_DIR}" && npm install)
fi

run_test() {
    local test_file="$1"
    local base_url="$2"
    local base_path="$3"
    local site_root="$4"
    local name
    name="$(basename "$test_file")"
    echo ""
    echo "--- ${name} ---"
    BASE_URL="${base_url}" BASE_PATH="${base_path}" SITE_ROOT="${site_root}" \
        node "$test_file"
}

# ── Root site: generate, serve, run 210 + 211 ───────────────

ROOT_OUTPUT="/tmp/test-output"

echo "=== Generating root site via test 201 ==="
bash "${TESTSUITE_DIR}/run-test.sh" "${RUN_TEST_EXTRA_ARGS[@]}" --output "${ROOT_OUTPUT}" 201

if [[ ! -f "${ROOT_OUTPUT}/index.html" ]]; then
    echo "ERROR: Root site generation failed — no index.html in ${ROOT_OUTPUT}"
    exit 1
fi
echo "  ✓ Root site generated"

echo ""
echo "=== Browser tests: root site (/) ==="
start_vite "${ROOT_OUTPUT}" "/"
run_test "${TESTS_DIR}/210-browser-page-validation.mjs" "http://localhost:${PORT}" "/" "${ROOT_OUTPUT}"
run_test "${TESTS_DIR}/211-browser-parquet-loading.mjs"  "http://localhost:${PORT}" "/" "${ROOT_OUTPUT}"
stop_vite

# ── Subdir site: generate, serve, run 210 ────────────────────

SUBDIR_OUTPUT="/tmp/test-output-subdir"
rm -rf "${SUBDIR_OUTPUT}"
mkdir -p "${SUBDIR_OUTPUT}"

echo ""
echo "=== Generating subdir site (base_url: /myapp/) ==="
docker run --rm \
    -e POND=/pond \
    -e RUST_LOG=info \
    -v "${SUBDIR_OUTPUT}:/output" \
    -v "${TESTSUITE_DIR}/tests/205-sitegen-base-url.sh:/test/run.sh:ro" \
    -v "${TESTSUITE_DIR}/testdata:/data:ro" \
    duckpond-test:latest \
    -c "/bin/bash /test/run.sh && cp -r /tmp/sitegen-subdir/* /output/" > /tmp/test-202-subdir.log 2>&1

if [[ ! -f "${SUBDIR_OUTPUT}/index.html" ]]; then
    echo "ERROR: Subdir site generation failed — no index.html"
    echo "Log:"
    tail -20 /tmp/test-202-subdir.log
    exit 1
fi
echo "  ✓ Subdir site generated"

echo ""
echo "=== Browser tests: subdir site (/myapp/) ==="
start_vite "${SUBDIR_OUTPUT}" "/myapp/"
run_test "${TESTS_DIR}/210-browser-page-validation.mjs" "http://localhost:${PORT}" "/myapp/" "${SUBDIR_OUTPUT}"
stop_vite

# ── Overlay site: generate, serve, run 305 ───────────────────

OVERLAY_OUTPUT="/tmp/test-output-overlay"
rm -rf "${OVERLAY_OUTPUT}"
mkdir -p "${OVERLAY_OUTPUT}"

echo ""
echo "=== Generating overlay site via test 305 ==="
bash "${TESTSUITE_DIR}/run-test.sh" "${RUN_TEST_EXTRA_ARGS[@]}" --output "${OVERLAY_OUTPUT}" 305

if [[ ! -f "${OVERLAY_OUTPUT}/analysis/pump-cycles.html" ]]; then
    echo "ERROR: Overlay site generation failed — no pump-cycles.html"
    exit 1
fi
echo "  ✓ Overlay site generated"

echo ""
echo "=== Browser tests: overlay site ==="
start_vite "${OVERLAY_OUTPUT}" "/"
run_test "${TESTS_DIR}/305-browser-overlay-chart.mjs" "http://localhost:${PORT}" "/" "${OVERLAY_OUTPUT}"
stop_vite

echo ""
echo "=== All browser tests PASSED ==="
