import { defineConfig } from "vite";
import { realpathSync } from "fs";

// SITE_ROOT points to a directory of static files generated by sitegen.
// We resolve symlinks (macOS /tmp → /private/tmp) so Vite can find them.
const siteRoot = process.env.SITE_ROOT
  ? realpathSync(process.env.SITE_ROOT)
  : ".";

export default defineConfig({
  appType: "mpa",
  root: siteRoot,
  // The site is fully static — no bundling, no transforms.
  build: { rollupOptions: { input: {} } },
});
