import { defineConfig } from "vite";
import { realpathSync } from "fs";

// SITE_ROOT points to a directory of static files generated by sitegen.
// We resolve symlinks (macOS /tmp → /private/tmp) so Vite can find them.
const siteRoot = process.env.SITE_ROOT
  ? realpathSync(process.env.SITE_ROOT)
  : ".";

// BASE_PATH controls the URL prefix (e.g., "/" or "/myapp/").
// Vite serves files at this path, simulating a subdir deployment.
const basePath = process.env.BASE_PATH || "/";

export default defineConfig({
  appType: "mpa",
  root: siteRoot,
  base: basePath,
  // The site is fully static — no bundling, no transforms.
  build: { rollupOptions: { input: {} } },
  // Disable HMR and file watching — the site is pre-generated static content.
  // Without this, Vite's watcher can trigger page reloads mid-test (e.g., if
  // macOS writes .DS_Store or another process touches the directory), which
  // destroys Puppeteer's execution context.
  server: {
    hmr: false,
    watch: null,
  },
});
